version: '3'
services:
  app:
    restart: always
    build: ./
    depends_on:
      - mongo
    ports:
      - '80:8000'
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
